{% set name = "scikit-optimize" %}
{% set version = "0.6" %}
{% set sha256 = "5bdbb73ca344e3a8a4487ab96a9b262d882d693f1edeb8ffab003f7f97bd540b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip

  run:
    - python
    - numpy
    - pyyaml
    - scipy >=0.14.0
    - scikit-learn >=0.19.1
    - matplotlib

test:
  imports:
    - skopt
    - skopt.learning
    - skopt.learning.gaussian_process
    - skopt.optimizer
    - skopt.space

about:
  home: https://scikit-optimize.github.io/
  license_file: LICENSE.md
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Sequential model-based optimization toolbox.'
  dev_url: https://github.com/scikit-optimize/scikit-optimize
  doc_url: https://scikit-optimize.github.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ukaratay
    
    
