{% set name = "scikit-optimize" %}
{% set version = "0.4" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c01d5b9f31105172067b1df18d15c277a15c81580317c2b002d8e63df6216156" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy
    - scipy >=0.14.0
    - scikit-learn >=0.18
    - matplotlib

test:
  imports:
    - skopt
    - skopt.learning
    - skopt.learning.gaussian_process
    - skopt.optimizer
    - skopt.space

about:
  home: https://scikit-optimize.github.io/
  # No manifest in original - see https://github.com/scikit-optimize/scikit-optimize/pull/447
  license_file: {{ RECIPE_DIR }}/LICENSE.md
  license: BSD 3-Clause
  license_family: BSD
  summary: 'Sequential model-based optimization toolbox.'
  dev_url: https://github.com/scikit-optimize/scikit-optimize
  doc_url: https://scikit-optimize.github.io/

extra:
  recipe-maintainers:
    - pmlandwehr
