{% set name = "scikit-optimize" %}
{% set version = "0.10.0" %}
{% set sha256 = "b1cc4ad8de1b3b33c09713f45b642ed17ce2ae749aca8900ed7e3c8dce63baa1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - scipy >=0.14.0
    - scikit-learn >=0.19.1
    - matplotlib-base
    - pyaml
    - joblib

test:
  imports:
    - skopt
    - skopt.learning
    - skopt.learning.gaussian_process
    - skopt.optimizer
    - skopt.space
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://scikit-optimize.github.io/
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Sequential model-based optimization toolbox.
  dev_url: https://github.com/scikit-optimize/scikit-optimize
  doc_url: https://scikit-optimize.github.io/

extra:
  recipe-maintainers:
    - ukaratay
    - holgern
