{% set name = "scikit-optimize" %}
{% set version = "0.9.0" %}
{% set sha256 = "77d8c9e64947fc9f5cc05bbc6aed7b8a9907871ae26fe11997fd67be90f26008" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip

  run:
    - python
    - numpy
    - scipy >=0.14.0
    - scikit-learn >=0.19.1
    - matplotlib-base
    - pyaml
    - joblib

test:
  imports:
    - skopt
    - skopt.learning
    - skopt.learning.gaussian_process
    - skopt.optimizer
    - skopt.space

about:
  home: https://scikit-optimize.github.io/
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Sequential model-based optimization toolbox.
  dev_url: https://github.com/scikit-optimize/scikit-optimize
  doc_url: https://scikit-optimize.github.io/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ukaratay
    - holgern

